### ISSUE TITLE
Broken old URLs

### ISSUE THREAD

**Issue by andreslucena** [AjuntamentdeBarcelona/decidim-barcelona#111]
#### :tophat: User Story

As an user, when I go to an old URL like http://decidim.barcelona/pam/action_plans/5058 I get a 404. 

I should get a redirect to the new URL (https://www.decidim.barcelona/processes/1/f/8/results/5058). 

This is important because there are a lot of official documents that have the same kind of URLs.

**Comment by oriolgual** [comment]
@andreslucena do you have a list of pattern we should redirect?

**Comment by andreslucena** [comment]
@oriolgual I'm afraid we don't have the patterns, just the old URLs that we are finding. Another one is: 

https://www.decidim.barcelona/metadecidim/62/proposals/enquestes
