### ISSUE TITLE
translation missing on user roles options

### ISSUE THREAD

**Issue by josanFFiG** [AjuntamentdeBarcelona/decidim-barcelona#112]
#### :tophat: User Story

Translation missing on user roles options within a process...
Not displayed in any language.
Current message shown: translation missing: ca.decidim.admin.model....

**Comment by mrcasals** [comment]
Hi @josanFFiG! Can you give as a URL so we can check this?

**Comment by josanFFiG** [comment]
Hi @mrcasals here you have: https://www.decidim.barcelona/admin/participatory_processes/23/user_roles/new

**Comment by mrcasals** [comment]
This will be fixed with #110. Also, we're discussing how to deal with translation missing problems here: https://github.com/decidim/decidim/issues/1309
