### ISSUE TITLE
Script to migrate from Decidim::Results to Decidim::Accountability

### ISSUE THREAD

**Issue by amaia** [AjuntamentdeBarcelona/decidim-barcelona#116]
Make a script to copy all records from Decidim::Results::Result to Decidim::Accountability::Result maintaining ids (to keep the match with the Project Monitor data).

This is more specific to Barcelona, so the script will not be part of the Decidim::Accountability engine, but I'm recording it here to have a list of pending tasks.

@xabier @andreslucena @josepjaume @oriolgual when the time comes who will be doing the data migration? Will we (@PopulateTools) have access to the server to do it? Or at least a staging server to test the script?

Copied from original issue: decidim/decidim-accountability#10

**Comment by amaia** [comment]
This is the script I've used to test in the heroku staging server (run through console or rails runner). The accountability feature in the PAM process has to be (manually) created before running the script.

@xabier @andreslucena @josepjaume @oriolgual do you want it to be part of the repo as a rake task or something like that? Something else? How do you want to organize the migration? 

```ruby
pam_process = Decidim::ParticipatoryProcess.find(1)

results_feature = pam_process.features.where(manifest_name: 'results').first

accountability_feature = pam_process.features.where(manifest_name: 'accountability').first

Decidim::Results::Result.where(feature: results_feature).find_each do |result|
  accountability_result = Decidim::Accountability::Result.create!(
    id: result.id,
    feature: accountability_feature,
    scope: result.scope,
    category: result.category,
    title: result.title,
    description: result.description
  )

  proposals = result.linked_resources(:proposals, "included_proposals")
  accountability_result.link_resources(proposals, "included_proposals")

  meeting_ids = proposals.flat_map do |proposal|
    proposal.linked_resources(:meetings, "proposals_from_meeting").pluck(:id)
  end.uniq
  meetings = accountability_result.sibling_scope(:meetings).where(id: meeting_ids)
  accountability_result.link_resources(meetings, "meetings_through_proposals")
end
```

**Comment by josepjaume** [comment]
Nice job! A task in the `decidim-barcelona` repo looks fine to me 👍

**Comment by amaia** [comment]
@josepjaume thanks! I'll make a PR with a rake task :)

**Comment by amaia** [comment]
I've added the rake task as part of PR #117
