### ISSUE TITLE
Searching, filtering and validating organizations

### ISSUE THREAD

**Issue by josanFFiG** [AjuntamentdeBarcelona/decidim-barcelona#118]
#### :tophat: User Story

In order to facilitate organizations' verification process, in previous versions we used to had a searching engine and filtering engine which made easier this process
We need to restore this in order to be able to:
     - Search organizations by name
     - Filter by validation state:
         · pending;
         · rejected;
         · validated;
     - and finally, to be able to change validation state.

**Comment by andreslucena** [comment]
This probably belongs to decidim/decidim, as a is a general use case (almost every city council would like this feature)

**Comment by lastpotion** [comment]
This issue was moved to decidim/decidim#1408
