### ISSUE TITLE
Comment notifications on PROPOSALS

### ISSUE THREAD

**Issue by josanFFiG** [AjuntamentdeBarcelona/decidim-barcelona#129]
#### :tophat: User Story

Users (either person or organization) who have made a proposal in an open process, are not receiving any notification, when another user makes a comment, despite having turned on notification options panel on user settings.

**Comment by oriolgual** [comment]
@josanFFiG could you please add an example proposal were you've detected this?

**Comment by josanFFiG** [comment]
@oriolgual here you have an example: 
https://www.decidim.barcelona/processes/24/f/66/proposals/11835

**Comment by beagleknight** [comment]
Hi Josan!
I made a revision of the issue and I checked the platform we are using to send the emails and a notification was sent to `fem***val@fem***val.com` at Jun 8, 2017 12:45:14 PM
Have the user checked the spam folder?
Thanks!

**Comment by josanFFiG** [comment]
@beagleknight sure they have.
In fact I did it myself, because I work there part time, that's why I choose that proposal to comment.

**Comment by beagleknight** [comment]
Well.. it seems the email is stucked in someplace 😄 . Any ideas @josepjaume ?

**Comment by josanFFiG** [comment]
I have done another test using "I don't renember my password" and it works properly.

**Comment by beagleknight** [comment]
We have tested the feature and it seems to work properly. @josanFFiG it looks like a one-off error so I'm closing the issue for now. Don't hesitate to open it again or report a new one if the error persists.

**Comment by josanFFiG** [comment]
Thank you @beagleknight we will open it again or report a new one if the error persists, as you suggest.
