### ISSUE TITLE
Comment notifications on RESULTS

### ISSUE THREAD

**Issue by josanFFiG** [AjuntamentdeBarcelona/decidim-barcelona#130]
#### :tophat: User Story

The authors of results -regardless of the role they have been assigned (user, contributor, administrator)- must receive notifications of any comment made by another user.

**Comment by oriolgual** [comment]
@josanFFiG the thing is that results don't have an author. Who should receive the notifications? All the process admins?

**Comment by josanFFiG** [comment]
@oriolgual Admins would be ok by now.
