### ISSUE TITLE
Sharing Link Option

### ISSUE THREAD

**Issue by josanFFiG** [AjuntamentdeBarcelona/decidim-barcelona#135]
#### :tophat: User Story
Sharin Link Option is not working it is not show the link to share.
Tested on proposals and events.

#### :clipboard: Related documentation
![decidim_sharelink](https://user-images.githubusercontent.com/27766903/28077414-00ce83e2-6662-11e7-8bfc-e24e3a095707.png)

**Comment by beagleknight** [comment]
This issue was moved to decidim/decidim#1589
