### ISSUE TITLE
Static map for meetings doesn't work on every tenant 

### ISSUE THREAD

**Issue by andreslucena** [AjuntamentdeBarcelona/decidim-barcelona#137]
# This is a Bug Report

Creating this one on our installation, because I don't know if a misconfiguration on our side or it's on the framework. 

#### :tophat: Description
 
* What went wrong?
When I go to a meeting created on a multitenant, it doesn't show the static map. It doesn't happen on every tenant. 

* What did you expect should have happened?
To show the map on a meeting. 

* What was the config you used?
* What stacktrace or error message from your provider did you see?

> The image "[URL]” cannot be displayed because it contains errors.

#### :clipboard: Additional Data

* ***Decidim deployment where you found the issue***: decidim.barcelona
* ***Browser & version***:
* ***Screenshot***:
![image](https://user-images.githubusercontent.com/717367/28163392-38c453ac-67cb-11e7-97f3-2859b0c0bbd7.png)
* ***Error messages***:
> The image "[URL]” cannot be displayed because it contains errors.
* ***URL to reproduce the error***:
https://meta.decidim.barcelona/processes/33/f/92/meetings/895
https://meta.decidim.barcelona/static_map?sgid=BAh7CEkiCGdpZAY6BkVUSSI7Z2lkOi8vZGVjaWRpbS1iYXJjZWxvbmEvRGVjaWRpbTo6TWVldGluZ3M6Ok1lZXRpbmcvODk1BjsAVEkiDHB1cnBvc2UGOwBUSSIMZGVmYXVsdAY7AFRJIg9leHBpcmVzX2F0BjsAVEkiHTIwMTctMDgtMTNUMTA6NTU6MjYuNzQyWgY7AFQ%3D--35accc5cab52a5e4e6b1c204c18a4e66b86eb930

**Comment by beagleknight** [comment]
The URL is working fine for me. Is it working for you right now @andreslucena ?

**Comment by mrcasals** [comment]
@beagleknight @andreslucena it's working fine for me too, but I saw it failing when the issue was opened :/ Did we deploy a new version that somehow fixed this?

**Comment by beagleknight** [comment]
@mrcasals I don't think so 🤔 . I don't remember tweaking anything about maps so my guess is it was something related to the configuration maybe?

**Comment by andreslucena** [comment]
Yes, it's working now. Maybe it was a regression fixed with the release 0.4.0 

I'm closing this issue.
