### ISSUE TITLE
Problem when uploading avatar image

### ISSUE THREAD

**Issue by xabier** [AjuntamentdeBarcelona/decidim-barcelona#157]
# This is a bug report

When trying to upload an image into my user profile to be used as an Avatar, weirdly the page asks me to introduce the password again, when I do I get back to the first step, not being capable to update my profile with my image.

![image](https://user-images.githubusercontent.com/537284/31844358-71acd2d6-b5f8-11e7-89b6-2ac233f64253.png)

I can reproduce this once and again.

**Comment by mrcasals** [comment]
@xabier are you entering your password here? If you don't want to change it, do not enter it, and you'll be able to change your avatar correctly. Maybe we can move the password fields to another side tab 😕

**Comment by xabier** [comment]
hi @mrcasals the problem is that Decidim forces me to update the password right after uploading the avatar image :( It is not something I force or select

**Comment by xabier** [comment]
It happens when I click "update account"

**Comment by mrcasals** [comment]
Even if you leave both password fields blank?

**Comment by xabier** [comment]
I don't have the password field visible when I push the update account button.

![image](https://user-images.githubusercontent.com/537284/31931287-04cf9e52-b8a3-11e7-84de-28f127b7af12.png)

**Comment by xabier** [comment]
Maybe it has to do with having the password stored on Firefox?

**Comment by mrcasals** [comment]
Ah, sure, that'll be the problem. Can you try uploading your avatar, then opening the password fields and ensuring they are blank?

As I said, we could probably move the password fields into another tab to avoid this problem /cc @josepjaume

**Comment by josepjaume** [comment]
It's strange, I've just uploaded my avatar in `decidim.barcelona` without further issues!

**Comment by josepjaume** [comment]
@xabier can you tell me the format & size of the file? Maybe it has to do with that.

**Comment by xabier** [comment]
it has to do with having the password stored! I uploaded the image, then clicked on "change password", then deleted the stored password leaving both fields blank, and it all worked :smile: 

but this is a usability issue, needs to be solver: +1 to creating a new section to change the password. Also because profile page will be enriched soon

**Comment by mrcasals** [comment]
This issue was moved to decidim/decidim#2105
