### ISSUE TITLE
District names not shown on users/citizens verification form 

### ISSUE THREAD

**Issue by josanFFiG** [AjuntamentdeBarcelona/decidim-barcelona#162]
#### :tophat: User Story

District names not shown on users/citizens verification form, instead there's a list of numbers.
Although numbers are related to districts, normally a citizen don't know this relation, so what should be shown are District names.

#### :clipboard: Related documentation

![captura de 2017-10-25 13-47-25](https://user-images.githubusercontent.com/27766903/31997594-d696c26e-b98c-11e7-89d3-3cc8e38dec74.png)

**Comment by andreslucena** [comment]
It isn't working on production, same error:

![imatge](https://user-images.githubusercontent.com/717367/32319466-f2ad9c6e-bfba-11e7-8188-916916f696fd.png)

**Comment by josepjaume** [comment]
Sorry deployment issues. It's working correctly now.
