### ISSUE TITLE
Verification with NIE doesn't work 

### ISSUE THREAD

**Issue by andreslucena** [AjuntamentdeBarcelona/decidim-barcelona#169]
#### :tophat: User Story

When I go to verify my residence with a NIE I get an error that the document number is incorrect. It isn't. It fails with at least 2 different users. 

#### :clipboard: Related documentation

![imatge](https://user-images.githubusercontent.com/717367/32725932-539304be-c877-11e7-8218-78a4a254ab9c.png)

#### :dart: Acceptance criteria
NIE residence verification should work.

**Comment by andreslucena** [comment]
It was a problem on layer 8 (the user wasn't on the municipal census database). Closing this issue.

**Comment by viktorsmari** [comment]
Is it possible to get an error message, telling you are not on that database?
I think that might be my case. 
Also, should you or should you not, have the last 2 letters like '-A'? 
It would be nice to have a placeholder with an example.
