### ISSUE TITLE
videos doesn't display in website

### ISSUE THREAD

**Issue by josanFFiG** [AjuntamentdeBarcelona/decidim-barcelona#171]
#### :tophat: User Story

Although videos are embedded on/through Control Panel, these doesn't display in frontend...
We have had already checked on different OS and Web Browsers.

#### :clipboard: Related documentation

Some examples:
- https://www.decidim.barcelona/processes/prova-pilot-pressupostos-participatius
![captura de 2017-11-13 12-59-08](https://user-images.githubusercontent.com/27766903/32730346-11eae652-c887-11e7-9126-05d59eb9661a.png)
- https://www.decidim.barcelona/processes/placlima/f/110/
![captura de 2017-11-13 13-00-25](https://user-images.githubusercontent.com/27766903/32730419-54f30a6a-c887-11e7-85ce-0f45f120d539.png)
- https://www.decidim.barcelona/processes/coproduccio-de-projectes-a-gracia
![captura de 2017-11-13 15-20-42](https://user-images.githubusercontent.com/27766903/32730441-66ef238e-c887-11e7-83b6-11f6e8de7a4e.png)

**Comment by mrcasals** [comment]
Reported in https://github.com/decidim/decidim/issues/2130.

**Comment by josanFFiG** [comment]
Sorry then @mrcasals !

**Comment by mrcasals** [comment]
No problem! 😄

**Comment by andreslucena** [comment]
I think this was fixed on last version update. @josanFFiG could you confirm it? Thanks

**Comment by mrcasals** [comment]
It was released on v0.8.0, so it should be working now on Barcelona.

**Comment by oriolgual** [comment]
Videos are working.
