### ISSUE TITLE
Proposals geocodification/ geolocation error

### ISSUE THREAD

**Issue by josanFFiG** [AjuntamentdeBarcelona/decidim-barcelona#176]
#### :tophat: User Story

Error message trying to add and address on a proposal.

#### :clipboard: Related documentation
seen on decidim.coterrats.com
![captura de 2017-11-27 11-36-09](https://user-images.githubusercontent.com/27766903/33262727-9f60982a-d367-11e7-837a-3044863db06c.png)

**Comment by oriolgual** [comment]
Sorry for the delay @josanFFiG, fixed.
