### ISSUE TITLE
Fix initiative's initializer

### ISSUE THREAD

**Issue by jsperezg** [AjuntamentdeBarcelona/decidim-barcelona#182]
#### :tophat: User Story

The content of config/initializers/initiatives.rb is wrong. It should content the following values:

```ruby
# frozen_string_literal: true

Decidim::Initiatives.configure do |config|
  config.face_to_face_voting_allowed = true
  config.online_voting_allowed = false
end
```

**Comment by josepjaume** [comment]
OMG I'm so sorry about this :(

**Comment by josepjaume** [comment]
Fixed in https://github.com/AjuntamentdeBarcelona/decidim-barcelona/commit/34dc4460ea3655978706bfbd230649ff7c8404be

**Comment by jsperezg** [comment]
No worries. This is a team responsibility and I’ve been also busy with sortitions module

Good job!
