### ISSUE TITLE
Results funcionality is missing

### ISSUE THREAD

**Issue by josanFFiG** [AjuntamentdeBarcelona/decidim-barcelona#184]
#### :tophat: User Story
While configuring of a new process: https://www.decidim.barcelona/processes/lesrambles adding functionalities I couldn't find Results on functionalities list.

#### :clipboard: Related documentation
![captura de 2018-01-03 13-01-54](https://user-images.githubusercontent.com/27766903/34519836-51600e94-f086-11e7-961a-53f6298bc47c.png)

**Comment by oriolgual** [comment]
@josanFFiG the results feature was deprecated by accountability (Seguiment).
