### ISSUE TITLE
Add staging environment

### ISSUE THREAD

**Issue by mrcasals** [AjuntamentdeBarcelona/decidim-barcelona#186]
#### :tophat: User Story
We want to have a staging environment. It should only be accessible with a given user/password combination.

#### :clipboard: Related documentation
None

#### :dart: Acceptance criteria
The same Rails app is deployed in two different Heroku apps: staging & production. Both apps can be at different git commits.

#### :pushpin: Related issues
None

**Comment by andreslucena** [comment]
@mrcasals is it done? could this issue be closed?
