### ISSUE TITLE
500 error on Page

### ISSUE THREAD

**Issue by andreslucena** [AjuntamentdeBarcelona/decidim-barcelona#188]
#### :tophat: User Story

When I go to a page it gives a 500 error. This only occurs with Spanish locale. 

#### :clipboard: Related documentation
https://www.decidim.barcelona/processes/Repensem22a/f/168/?locale=es

#### :dart: Acceptance criteria
It shouldn't give this error

**Comment by oriolgual** [comment]
I can't reproduce it :/

**Comment by mrcasals** [comment]
Me neither:

![](https://i.imgur.com/yo7EXwg.png)

**Comment by andreslucena** [comment]
Me neither, seems like a Heisenbug. Closing this issue.
