### ISSUE TITLE
Social Login broken with Facebook

### ISSUE THREAD

**Issue by andreslucena** [AjuntamentdeBarcelona/decidim-barcelona#215]
#### :tophat: User Story

When I try to sign in with social login with FB I get an error. Seems like it's misconfigured 

#### :clipboard: Related documentation

![imagen](https://user-images.githubusercontent.com/717367/40351033-b6a5894a-5dab-11e8-8567-bfa6e7d172b4.png)

#### :dart: Acceptance criteria

It should work

#### :pushpin: Related issues

N/A

**Comment by oriolgual** [comment]
Fixed! We've updated the docs so other users know how to set it up: https://github.com/decidim/decidim/pull/3474
