### ISSUE TITLE
GraphiQL is not working

### ISSUE THREAD

**Issue by elaragon** [AjuntamentdeBarcelona/decidim-barcelona#243]
#### :tophat: User Story

The in-browser IDE for exploring the GraphQL API is not working, see https://www.decidim.barcelona/api/graphiql. 

This is a particular issue of decidim.barcelona (for instance, https://meta.decidim.org/api/graphiql is OK)

![captura de pantalla de 2019-01-17 12-12-24](https://user-images.githubusercontent.com/3785819/51314880-2c55bb80-1a51-11e9-825b-300b0a7ba3d7.png)

**Comment by tramuntanal** [comment]
I'm closing this issue because is now working 
![image](https://user-images.githubusercontent.com/199462/82049542-c87beb00-96b6-11ea-923b-348a3e381c2d.png)
