### ISSUE TITLE
Missing links on footer

### ISSUE THREAD

**Issue by andreslucena** [AjuntamentdeBarcelona/decidim-barcelona#27]
#### :tophat: User Story

There are some links missing on the default layout: the social media icons on the footer. 

Old version: 
![imatge](https://cloud.githubusercontent.com/assets/717367/22546647/392af1b8-e93e-11e6-96cf-41b659c2dbe4.png)

New version: 
![imatge](https://cloud.githubusercontent.com/assets/717367/22546661/4e73dbd4-e93e-11e6-9ed8-00b1eb71bfd7.png)

**Comment by andreslucena** [comment]
I don't know if this should be an issue on decidim project. Ideally this should be editable through the Admin general Configuration.

**Comment by oriolgual** [comment]
@andreslucena the footer links are links created automatically from pages created at the admin, so basically what we need to do is import the static pages from decidim.barcelona to a Decidim::Page

**Comment by oriolgual** [comment]
Oh, and find a way to inject the social icons (that's probably Decidim-related)

**Comment by mrcasals** [comment]
https://github.com/AjuntamentdeBarcelona/decidim/issues/769

**Comment by mrcasals** [comment]
Moved to `decidim` for better discussion: https://github.com/AjuntamentdeBarcelona/decidim/issues/769
