### ISSUE TITLE
Change "More information" link in homepage

### ISSUE THREAD

**Issue by carolromero** [AjuntamentdeBarcelona/decidim-barcelona#33]
#### :tophat: User Story
The link of "More Information" button in homepage should be updated with correct url:
Now: https://decidim.barcelona/pages/faq
Correct: https://decidim.barcelona/pages/more-information

#### :clipboard: Related documentation
![imagen](https://cloud.githubusercontent.com/assets/23509895/22656310/443fd494-ec93-11e6-8c32-cdcc83093ce5.png)

#### :pushpin: Related issues

**Comment by oriolgual** [comment]
I think we need another approach for this, since the faq or more information pages are optional.

**Comment by andreslucena** [comment]
Two possible solutions: 

A) Maybe this kind of links must be configurable through the admin interface. For instance this is how Discourse does it: 

![imatge](https://cloud.githubusercontent.com/assets/717367/22742747/31fd90f6-ee18-11e6-9944-ae3344c16570.png)

B) Another possibility is to have some pages that must always be on the site (as FAQ, TOS, etc).

-------

I think A) is more open (for instance what if I only want to have one centralized TOS on another domain?).

**Comment by carolromero** [comment]
I think that a combination of the two choices would be ideal.

For example, a FAQ section should always be available and is somehow platform-specific. In fact I made a basic template to send to local councils as a starting point.

Instead, there are other pages such as Accessibility or other terms of service that may be hosted in another domain.

**Comment by oriolgual** [comment]
Actually, B is already implemented (faq, tos & accessibility), but with the migration we didn't create them!

**Comment by oriolgual** [comment]
Maybe we can change the slug (URL) of the more information page to faq?
