### ISSUE TITLE
Projects voting: scopes should depend on the process

### ISSUE THREAD

**Issue by andreslucena** [AjuntamentdeBarcelona/decidim-barcelona#36]
#### :tophat: User Story

Right now I can see the Ambit scope for filtering on all the Projects. This doesn't have much sense because this votings for this processes is always on only one district: 

![imatge](https://cloud.githubusercontent.com/assets/717367/22730518/9b92c1ca-ede7-11e6-962e-2a9dcfc85b1e.png)

#### :dart: Acceptance criteria

I should not see this filters on this processes.

**Comment by mrcasals** [comment]
Possibly duplicated of https://github.com/AjuntamentdeBarcelona/decidim/issues/806

**Comment by andreslucena** [comment]
Uops, that's right, closing this one.
