### ISSUE TITLE
All the meetings of the Xarxa Bus Process have been delayed one hour

### ISSUE THREAD

**Issue by arnaumonty** [AjuntamentdeBarcelona/decidim-barcelona#41]
#### :tophat: User Story
All the meetings of the Xarxa Bus Process have been delayed one hour

#### :clipboard: Related documentation
[Meetings page](https://decidim.barcelona/processes/10/f/20)

**Comment by oriolgual** [comment]
Will be fixed with https://github.com/AjuntamentdeBarcelona/decidim/pull/861 (although we'll need to update them manually at the database)

**Comment by oriolgual** [comment]
I've updated them through the console.

**Comment by mrcasals** [comment]
@oriolgual can we close this? Should be fixed by now, since `decidim` was updated here after merging the linked PR.

**Comment by arnaumonty** [comment]
I think that all the meetings are ok.

**Comment by mrcasals** [comment]
Closing this, then
