### ISSUE TITLE
Repeated content in the home description area

### ISSUE THREAD

**Issue by JuanLi1979** [AjuntamentdeBarcelona/decidim-barcelona#52]
<img width="1147" alt="captura de pantalla 2017-02-13 a las 16 29 39" src="https://cloud.githubusercontent.com/assets/22983668/22889599/0085947e-f20a-11e6-957b-81a65ad58a18.png">

Trobades and Debats have the same text. Debats text must be: "Espais per informar-te i decidir sobre les propostes de cada procés"

**Comment by JuanLi1979** [comment]
The same for the español version

**Comment by oriolgual** [comment]
Related to #33
