### ISSUE TITLE
PAM visualisations

### ISSUE THREAD

**Issue by oriolgual** [AjuntamentdeBarcelona/decidim-barcelona#54]
#### :tophat: User Story

After the migration we lost the dataviz documents data from the PAM. We need a way to integrate it, either via a page or a custom component that includes the iframe.

#### :clipboard: Related documentation

https://decidimbcn-production.herokuapp.com/pam/6/dataviz/summary

#### :dart: Acceptance criteria

PAM has the dataviz included.

**Comment by mrcasals** [comment]
What about adding an `Iframe` component to `decidim`? Is it worth it having it everywhere, or is it enough having it just for Barcelona?

**Comment by oriolgual** [comment]
I wouldn't try to generalise something like this, we shouldn't encourage adding iframes.

**Comment by oriolgual** [comment]
Just to reinforce it: this component shouldn't have any admin nor options, it's just a special case for the PAM.

**Comment by andreslucena** [comment]
I'm with @oriolgual 
At the moment it's not necessary to make an iframe component, maybe on the future it could be something interesting to have. Some platforms do this, like Open Irekia with COM-T integration. Right now, let's apply YAGNI.
