### ISSUE TITLE
Query aggregated verification data from the admin panel, filtered by periods and dates

### ISSUE THREAD

**Issue by NilHomedes** [AjuntamentdeBarcelona/decidim-barcelona#548]
**Is your feature request related to a problem? Please describe.**
On some occasions, it is necessary to know the sociodemographic data of the participants in a process. Currently, this data can be obtained from the verification form. That is, if you ask for the date of birth, gender, and postal code during the verification, you can then aggregate this data to know the sociodemographic profile of the participants. 

Currently, to do this, it is necessary for a developer to create a query that allows decrypting this information. In Barcelona we are using this module to do that: https://github.com/AjuntamentdeBarcelona/decidim-barcelona/tree/master/decidim-stats 

**Describe the solution you'd like**
I want a feature that allows me to download an export file with all the verification data of a specific process or component. I should receive an email with the export file. So I can easily study the sociodemographics of a concrete participatory process. 

The file should contain all records in an anonymized form. It’s very important to export these data without linking them to a participant account, so we preserve participants privacy.  

This development should be an improvement of the existing module  https://github.com/AjuntamentdeBarcelona/decidim-barcelona/tree/master/decidim-stats 

**Describe alternatives you've considered**
Extract this data through a query. But, as an admin, I don’t want to rely on developers. 

**Additional context**

**Does this issue could impact on users private data?**
Yes, as we are importing personal data. It is very important to not link these data to a participant account.

**Acceptance criteria**

- [x]  Given I’m an admin
When I access to the authorizations page 
Then I can select an authorization method and define an start and end date.
- [x]  Given I’m an admin
When I have defined an authorization method and a start and end date
Then I can click on a CTA to export the verification data.
- [x]  Given I’m an admin
When I requested a verification data export 
Then a message appears saying “Your export is currently in progress. You will receive an email when it is complete.”
- [x]  Given I requested a verification data export 
When the request is completed 
Then I receive an email with the export file.
- [x]  Given I requested a verification data export of a specific time period
When the request is completed 
Then I receive an email with the export file with the data of that time period.
- [x]  Given an authorization is enabled with certain fields
When I request a verification data export
Then the export file contains data of all the fields.
- [x]  Given I requested a verification data export 
When I receive the email with the export file
Then the file contains all the records anonymized.

**Comment by mllocs** [comment]
@NilHomedes There's any mockup for this issue?

**Comment by mllocs** [comment]
> So I can easily study the sociodemographics of a concrete participatory process.

Should we also add a Process selector apart from "I can select an authorization method and define an start and end date."?

**Comment by mllocs** [comment]
@NilHomedes some questions regarding the issue:

> I want a feature that allows me to download an export file with all the verification data of a specific process or component

There's any link between a User and a Process/Component? I thought Users were only linked to an Org, and can access any space in the org. 

On the other side, the authorizations page currently looks like this:

<img width="1240" alt="Screenshot 2024-09-25 at 14 08 40" src="https://github.com/user-attachments/assets/ff1760cc-218c-4eae-adb5-b33fe0eae29b">

Where would we add a form to export the census data? 

---

Regarding this being an improvement to https://github.com/AjuntamentdeBarcelona/decidim-barcelona/tree/master/decidim-stats, couldn't we add this feature to the decidim gem? Seems something that can be useful to any decidim instance.

**Comment by NilHomedes** [comment]
Hi @mllocs!

Yes here it is a concept proto:
![Frame 11657(1)](https://github.com/user-attachments/assets/a2d66f9b-62e9-425e-a921-4b2a7be9cae8)

> There's any link between a User and a Process/Component? I thought Users were only linked to an Org, and can access any space in the org.

Yes, in fact the link is at a component level, as you can define permissions for each component enabled. 
See, you can set a verification method for all the actions in proposals:
![Screenshot 2024-09-26 at 14-31-43 Edit permissions - Admin - Test Site for Lot2](https://github.com/user-attachments/assets/c38f780f-2109-4acf-bb52-43af221d5773)

The need is to know the sociodemographic data of a specific process or component. 
But by defining the date period we solve that need. As if you, as an admin, know that voting was enabled during a week, by checking the verifications made during that week you will know the sociodemographic data. 

The alternative, could be to add another field that allows you to select participatory space and component. So you can point to a specific component. Would that be very difficult to develop? 

> Regarding this being an improvement to [master/decidim-stats](https://github.com/AjuntamentdeBarcelona/decidim-barcelona/tree/master/decidim-stats?rgh-link-date=2024-09-25T12%3A10%3A56Z), couldn't we add this feature to the decidim gem? Seems something that can be useful to any decidim instance.

From my point of view, yes, of course. If you can do it, that would be wonderful.

**Comment by mllocs** [comment]
Great, thanks @NilHomedes for all the feedback.

There's one little caveat in this issue. 

There's lot of flexibility on how Authorization Handlers store the form metadata. That logic is defined in the class itself, for example: https://github.com/AjuntamentdeBarcelona/decidim-barcelona/blob/759c49d9c591014962eb68b0019a46fdfb18a01e/app/services/census_authorization_handler.rb#L35

This means that the metadata we store in the Authorization model is not homogeneous. It could be that one handler stores the birthday date as `date_of_birth` and another as `birthday_date` for example.  

When building the CSV to export that metadata, if we want to have a column to export the birthday, we need to guess what's the name of that metadata field... We could also export all the metadata fields in one single column, but that might not be as useful since it will be difficult to filter or extract data from that column. 

Thoughts? @NilHomedes cc @furilo

**Comment by NilHomedes** [comment]
Hey @mllocs !
Let's suppose the case of the `census_authorization_handler`
If we export all the metadata of this handler, what do we get? We could generate a csv where each column is a different metadata. This way it would be easy for admins to read the title of each column and analyse the one they want. 

In this case the columns would be the following:
- User Hash
- date_of_birth
- postal_code
- scope_name
- scope_id
- scope_code
- gender

Would this work? 

----
> The alternative, could be to add another field that allows you to select participatory space and component. So you can point to a specific component. Would that be very difficult to develop?

Regarding this. I've been talking with de Barcelona team, they would like to have the option to filter between process and components. Do you think we can add this to the AC?

**Comment by mllocs** [comment]
Regarding:

> they would like to have the option to filter between process and components. Do you think we can add this to the AC?

and

> in fact the link is at a component level, as you can define permissions for each component enabled.
See, you can set a verification method for all the actions in proposals:

@NilHomedes Let's say a component have x permissions; Let's say I select a component to export the verification data: would it mean to export the data from all users that have permissions to access that component? Should we take into account who has access to the space? We could do that but having permission to access a component doesn't mean they got verified specifically for that component.

**Comment by NilHomedes** [comment]
>@NilHomedes Let's say a component have x permissions; Let's say I select a component to export the verification data: would it mean to export the data from all users that have permissions to access that component? Should we take into account who has access to the space? We could do that but having permission to access a component doesn't mean they got verified specifically for that component.

We only want to know who has been verified to do that specific action. 
The question is: If I have a proposals component with `authorization_census`enabled, and, at the same time, an initiative with  `authorization_census`enabled. Is it possible to differentiate who has been verified only to vote in the proposal component? Does the authorization handler save this data?

The data we want is who have participated in a specific action. So, we don't care about the whole list of the census.

**Comment by mllocs** [comment]
> Is it possible to differentiate who has been verified only to vote in the proposal component? Does the authorization handler save this data?

I'd say that we don't have that information available... cc @andreslucena

**Comment by mllocs** [comment]
> In this case the columns would be the following:

> User Hash
> date_of_birth
> postal_code
> scope_name
> scope_id
> scope_code
> gender

@NilHomedes What are the scope columns? User Hash could be the Authorization Id for example?

**Comment by mllocs** [comment]
> https://github.com/AjuntamentdeBarcelona/decidim-barcelona/issues/548#issuecomment-2392955899

I'm assuming that these scope columns were added when we thought that verifications were associated to a component, but it seems that they are not. The columns I'm exporting in [this PR](https://github.com/AjuntamentdeBarcelona/decidim-barcelona/pull/552) are defined [here](https://github.com/AjuntamentdeBarcelona/decidim-barcelona/pull/552/files#diff-f646b2d55ac8edf393cf29f7fb8107f7cc92953c01004be99ac70f60a93348adR13).

> id: authorization.id,
> name: authorization.name,
> granted_at: authorization.granted_at,
> postal_code: metadata["postal_code"],
> date_of_birth: metadata["date_of_birth"],
> gender: metadata["gender"]

**Comment by NilHomedes** [comment]
>@NilHomedes What are the scope columns? User Hash could be the Authorization Id for example?

These columns come from here: https://github.com/AjuntamentdeBarcelona/decidim-barcelona/blob/759c49d9c591014962eb68b0019a46fdfb18a01e/app/services/census_authorization_handler.rb#L35

It would change depending on the authorization fields. 

I was suggesting User Hash as a way to have a unique identifier for each verification in an anonymous way. It is important to preserve the anonymity of the participants. What are you suggesting to show in `authorization.granted_at` ? The date?

**Comment by mllocs** [comment]
> I was suggesting User Hash as a way to have a unique identifier for each verification in an anonymous way

Do you want an identifier that is _impossible_ to link back to the User but that would have the same value if a User has two verifications? Even impossible having access to the database?

**Comment by NilHomedes** [comment]
Yes, for privacy reasons, we do not want the identity of the verified persons to be known. This is essential to preserve participants privacy.

On the other hand, the csv will only be a verification method. 

> Given I’m an admin
When I access to the authorizations page
Then I can select an authorization method and define an start and end date

So, it's impossible that the same participant has been verified twice with the same authorization.

**Comment by NilHomedes** [comment]
>Then, what it's going to be used for? Maybe we don't need that hash at all, it's going to be a random string which won't add information to the user.

It will be used to analyse the socio-demographic data of the participants. For this, it is not necessary to know the name, nor is it necessary to know the user name. However, having a unique anonymous identifier would make the data more reliable.
