### ISSUE TITLE
500 error on Debates

### ISSUE THREAD

**Issue by mrcasals** [AjuntamentdeBarcelona/decidim-barcelona#56]
_From @andreslucena on February 15, 2017 11:34_

# This is a Bug Report

#### :tophat: Description

For bug reports:
* What went wrong? If I go to a Debate on the PAM process it doesn't work 
* What did you expect should have happened? To work 
* What stacktrace or error message from your provider did you see? 500 error

#### :pushpin: Related issues
* #813 
* #874 

#### :clipboard: Additional Data

* ***Decidim deployment where you found the issue***: decidim.barcelona
* ***Browser & version***: Firefox 51.0.1
* ***Screenshot***: 
* ***Error messages***: 500 error, "Hi ha hagut un problema amb el nostre servidor. Si us plau, torna-ho a intentar més tard."
* ***URL to reproduce the error***: https://decidim.barcelona/processes/1/f/9/debates/1  

_Copied from original issue: AjuntamentdeBarcelona/decidim#971_

**Comment by oriolgual** [comment]
Related to https://sentry.io/app62347735herokucom/production/issues/218888454/
