### ISSUE TITLE
Add video embeded in a page

### ISSUE THREAD

**Issue by arnaumonty** [AjuntamentdeBarcelona/decidim-barcelona#60]
#### :tophat: User Story

Embed [this video](https://www.youtube.com/watch?v=dy759mxfZZ4&feature=youtu.be) --> [here](https://decidim.barcelona/processes/3/f/23) under the text

#### :dart: Acceptance criteria
Show the thubnail of the video and open the video an emergent window

#### :pushpin: Related issues
https://github.com/AjuntamentdeBarcelona/decidim/issues/718

**Comment by mrcasals** [comment]
Working on it at https://github.com/AjuntamentdeBarcelona/decidim/pull/984

**Comment by mrcasals** [comment]
First PR is missing the button in the editor, the second related PR fixes it.
