### ISSUE TITLE
Comments missing on Debates

### ISSUE THREAD

**Issue by andreslucena** [AjuntamentdeBarcelona/decidim-barcelona#62]
#### :tophat: User Story

As a User when I go to a Debate I don't see the comments that people made. 

For instance:  https://decidim.barcelona/processes/1/f/9/debates/1

![imatge](https://cloud.githubusercontent.com/assets/717367/23019796/57ad6aba-f444-11e6-9702-863e984ae1fa.png)

#### :dart: Acceptance criteria

I should see the commetns there.

**Comment by mrcasals** [comment]
Might be related to #58, which is already being worked on.

**Comment by andreslucena** [comment]
Yes, it's the same, I'm closing this.
