### ISSUE TITLE
Problems creating new process

### ISSUE THREAD

**Issue by xabier** [AjuntamentdeBarcelona/decidim-barcelona#72]
#### :tophat: User Story

I tried to create a new participatory process (also @arnaumonty ). It was imposible. We need this relatively urgently. I used the same text for all the short and long descriptions because we needed to create a process and then handle the admin to somebody else to fill the form.

When trying to quickly fill some forms I clicked the "Create participatory process" button the system responded by  coloring in red some empty camps. After filling those when clicking the "Create participatory process" this was the result:

![image](https://cloud.githubusercontent.com/assets/537284/23406222/31bb66ee-fdbe-11e6-8fe8-b1176ab0ee9f.png)

#### :dart: Acceptance criteria
New processes can be created (not published) without all the information introduced beforehand

**Comment by josepjaume** [comment]
So what you're proposing is making the descriptions optional? Ok.

**Comment by josepjaume** [comment]
Processes are created unpublished, so it should be easier to fill in the text with a placeholder and then let someone finish it prior to publishing.

All the fields are mandatory by default in order to prevent incomplete or low-value processes from being published. But we can discuss how to handle missing data at the design level. I'm opening an issue on the framework.

**Comment by josepjaume** [comment]
Also, improvements in the admin panel will be done when implementing the admin design: https://decidim-design-admin.herokuapp.com/processes-new/

**Comment by xabier** [comment]
We are waiting forward to see the new admin panel implemented when money arrives, but this is a bug. The system fails to create the process, once the fields that appear in red are filled in. The system doesn't return the message "fields need to be filed to create process", this only happens for some fields. Do all the fields need to be filled in in order to create the process?

**Comment by mrcasals** [comment]
@xabier keep in mind that translations are compulsory in all the available locales for the current organization. Could it be that errors are hidden?

Otherwise if you can attach a screenshot of what are you seeing it would help us debug the issue :)

**Comment by xabier** [comment]
I also completed the translation, but @josepjaume informed me that the bug was already fixed :)

**Comment by mrcasals** [comment]
@xabier is this solved, then? Can we close this issue?

**Comment by arnaumonty** [comment]
@mrcasals  yes, it is solved (and you can close it) cc @xabier
